baseURL = "https://www.primeos.dev/"
languageCode = "en-us"
title = "Michael Weiss (primeos)"
theme = "primeos"

[params]
  homeSubtitle = "Computer science student and NixOS developer from Germany. Loves FOSS, mainly interested in GNU/Linux and computer networks."

  [[params.social]]
    name = "Email"
    url  = "mailto:michael@primeos.dev"
  [[params.social]]
    name = "XMPP"
    url  = "xmpp:primeos@jabber.ccc.de"
  # TODO (icon missing):
  #[[params.social]]
  #  name = "IRC"
  #  url  = "irc://irc.freenode.net/primeos,isuser"
  [[params.social]]
    name = "Matrix"
    url  = "matrix:user/primeos:matrix.org"
  [[params.social]]
    name = "GitHub"
    url  = "https://github.com/primeos"
  [[params.social]]
    name = "Pleroma"
    url  = "https://social.primeos.dev/michael"

[languages]
  [languages.en]
    #subtitle  = "Personal homepage"
    weight    = 1
    copyright = '<a href="https://creativecommons.org/licenses/by-sa/4.0/" target="_blank" rel="noopener">CC BY-SA 4.0</a>'

[menu]
  [[menu.main]]
    identifier = "about"
    name       = "About"
    url        = "about/"
